In [1]:
import pandas as pd

In [2]:
dataset = pd.read_parquet('../new_data/ais_val.parquet')

In [ ]:
        @tf.numpy_function(Tout=[tf.float32, tf.int32])
        def _one_hot_encode_track_messages(msgs):
    #        lat_bins = 200; lon_bins = 300; sog_bins = 30; cog_bins = 72
            def _one_hot_encode_track_message(msg):
                lat, lon, sog, cog = msg[0], msg[1], msg[2], msg[3]
                enc_msg_len = self.lat_bins + self.lon_bins + self.sog_bins + self.cog_bins
                enc_msg = np.zeros(enc_msg_len)
                enc_msg[int(lat*self.lat_bins)] = 1.0
                enc_msg[int(lon*self.lon_bins) + self.lat_bins] = 1.0
                enc_msg[int(sog*self.sog_bins) + self.lat_bins + self.lon_bins] = 1.0
                enc_msg[int(cog*self.cog_bins) + self.lat_bins + self.lon_bins + self.sog_bins] = 1.0
                return enc_msg
                    
            # msgs_[msgs_ == 1] = 0.99999 # legacy
            # one_hot_encoded_track_msgs = []
            one_hot_encoded_track_msgs = np.stack(list(map(_one_hot_encode_track_message, msgs)), dtype=np.float32, axis=0)
            return one_hot_encoded_track_msgs, np.int32(len(one_hot_encoded_track_msgs))

In [ ]:
from typing import Annotated

In [2]:
from pydantic import BaseModel
from typing import Callable, Annotated
from annotated_types import Len

class IterableWithLne

T = Annotated[Callable, Len]

class A(BaseModel):
    b : T

TypeError: '_ProtocolMeta' object is not iterable

In [ ]:
from pathlib import Path
from typing import Callable
from pydantic import Len

class InMemoryDatasetGenerator(Callable, Len):
    def __init__(self, parquet_file : Path):
        _ds = pd.read_parquet(parquet_file).replace(1, 0.9999)
        _ds.insert(0, 'temp_id', range(0, len(_ds)))
        _ds = _ds.set_index('temp_id', append=True)
        _ds = _ds.sort_index().reset_index(1).drop('temp_id', axis=1)
        _idxs = _ds.index.unique()

In [ ]:
import pandas as pd
parquet_file = '../new_data/ais_val.parquet'
def get_in_memory_dataset_generator():

    for idx in range(len(_idxs)):
        track = _ds.loc[_idxs[idx]].values
        yield track.reshape((-1, 4)).astype(np.float32)

In [1]:
import pandas as pd
parquet_file = '../new_data/ais_test.parquet'
_ds = pd.read_parquet(parquet_file)
_idxs = _ds.index.unique()
len(_idxs)

15814

In [2]:
import pandas as pd
parquet_file = '../new_data/ais_train.parquet'
_ds = pd.read_parquet(parquet_file)
_idxs = _ds.index.unique()
len(_idxs)

73795

In [3]:
import pandas as pd
parquet_file = '../new_data/ais_val.parquet'
_ds = pd.read_parquet(parquet_file)
_idxs = _ds.index.unique()
len(_idxs)

15813

In [292]:
b = TensorflowEncodedBatchedDatasetBuilder(
    track_generator=get_in_memory_dataset_generator, 
    batch_size=32,
    lat_bins=300,
    lon_bins=300, 
    sog_bins=30,
    cog_bins=72,
    shuffle=False
).build()

In [293]:
bi =iter(b)

In [354]:
next(bi)

(<tf.Tensor: shape=(25, 32, 702), dtype=float32, numpy=
 array([[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)>,
 <tf.Tensor: shape=(25, 32, 702), dtype=float32, numpy=
 array([[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)>,
 <tf.Tensor: shape=(32,), dtype=int32, numpy=
 array([ 7, 14,  7,  5,  6, 23, 18, 17, 25,  4, 12,  9, 22,  9, 24, 17,  3,
        12, 10, 15, 18,  4,  9,  9,  2,  9,  2,  6, 10,  4,  5, 21],
       dtype=int32)>)

In [ ]:
for a in get_in_memory_dataset_generator():

TypeError: InMemoryDataset.__init__() missing 1 required positional argument: 'parquet_file'

In [ ]:
a()

TypeError: 'generator' object is not callable

In [ ]:
dataset.insert(0, 'ordering', range(0, len(dataset)))

In [ ]:
dataset.loc[485510].values.shape

(16, 5)

In [ ]:
dataset = dataset.reset_index()

In [14]:
import tensorflow as tf

2025-07-17 12:22:37.511962: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1752754957.683328  442184 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1752754957.736820  442184 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1752754958.058704  442184 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1752754958.058730  442184 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1752754958.058733  442184 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1752754958.058734  442184 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-07-17 12:22:38.095199: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [ ]:
tf.Dataset.

In [ ]:
dataset[]

         track_id  latitude  longitude       cog       sog
0          468385  0.439220   0.476319  0.205000  0.350000
1            6543  0.741393   0.372603  0.206866  0.477981
2          223171  0.591464   0.283274  0.480534  0.038083
3          243903  0.559608   0.302818  0.000000  0.000000
4          469958  0.740083   0.290400  0.725698  0.484683
...           ...       ...        ...       ...       ...
1676198    485510  0.527826   0.490690  0.277778  0.336667
1676199    235501  0.550071   0.247371  0.259033  0.050045
1676200    387312  0.786784   0.453483  0.374855  0.383362
1676201    293511  0.553060   0.546981  0.938907  0.036667
1676202    424710  0.681334   0.467501  0.499654  0.290000

[1676203 rows x 5 columns]

In [ ]:
dataset.to_numpy()

array([[0.43922011, 0.47631886, 0.205     , 0.35      ],
       [0.74139259, 0.37260259, 0.20686585, 0.47798146],
       [0.59146373, 0.28327427, 0.48053418, 0.03808325],
       ...,
       [0.78678372, 0.45348311, 0.37485473, 0.3833615 ],
       [0.55305997, 0.54698139, 0.93890735, 0.03666667],
       [0.68133372, 0.46750136, 0.49965397, 0.29      ]])

In [ ]:
dataset.sort_index().values.T

(4, 1676203)

In [ ]:
dataset.sort_values('track_id').values.T

(5, 1676203)

Index([468385,   6543, 223171, 243903, 469958, 497296, 301185, 408128, 320944,
       348160,
       ...
       114543, 489135, 348650, 109454,  17485, 495527, 122022,  90319,  10735,
        12918],
      dtype='int64', name='track_id', length=105325)

In [ ]:
import numpy as np
def f(df):
    keys, values = df.sort_index().values.T
    ukeys, index = np.unique(keys, True)
    arrays = np.split(values, index[1:])
    
    return df2

In [4]:
15813 // 32

494

In [5]:
73795 // 32

2306

In [ ]:
dataset

          latitude  longitude       cog       sog
track_id
468385    0.439220   0.476319  0.205000  0.350000
6543      0.741393   0.372603  0.206866  0.477981
223171    0.591464   0.283274  0.480534  0.038083
243903    0.559608   0.302818  0.000000  0.000000
469958    0.740083   0.290400  0.725698  0.484683
...            ...        ...       ...       ...
485510    0.527826   0.490690  0.277778  0.336667
235501    0.550071   0.247371  0.259033  0.050045
387312    0.786784   0.453483  0.374855  0.383362
293511    0.553060   0.546981  0.938907  0.036667
424710    0.681334   0.467501  0.499654  0.290000

[1676203 rows x 4 columns]

In [ ]:
dataset.groupby(by='track_id').apply(list)

track_id
11        [latitude, longitude, cog, sog]
239       [latitude, longitude, cog, sog]
299       [latitude, longitude, cog, sog]
332       [latitude, longitude, cog, sog]
339       [latitude, longitude, cog, sog]
                       ...
511822    [latitude, longitude, cog, sog]
511825    [latitude, longitude, cog, sog]
511826    [latitude, longitude, cog, sog]
511828    [latitude, longitude, cog, sog]
511829    [latitude, longitude, cog, sog]
Length: 105325, dtype: object