In [1]:
import pandas as pd

In [11]:
for sub in  ['test', 'train', 'val']:
    parquet = f'../new_data/ais_{sub}_arrow.parquet'
    _ds = pd.read_parquet(parquet, columns=['latitude', 'longitude', 't'])
    _ds = _ds.set_index('t',append=True)
    _ds['latitude'] = (300 * _ds['latitude']).astype('uint16')
    _ds['longitude'] = (300 * _ds['longitude']).astype('uint16')
    _ds = _ds.rename({'latitude': 'lat_bin', 'longitude': 'lon_bin'})
    _ds.to_parquet(f'../new_data/ais_{sub}_by_bins.parquet')

In [7]:
_ds.index.levels[0]

Index([   239,    299,    332,    358,    404,    447,    459,    468,    481,
          488,
       ...
       511605, 511628, 511641, 511648, 511651, 511684, 511695, 511727, 511742,
       511825],
      dtype='int64', name='track_id', length=15814)

In [8]:
_ds

             latitude  longitude
track_id t
239      0   0.563266   0.291609
         1   0.562646   0.287027
         2   0.562080   0.282530
         3   0.562011   0.278010
         4   0.562501   0.273443
...               ...        ...
511825   57  0.632873   0.022723
         58  0.633535   0.015191
         59  0.635315   0.010628
         60  0.637340   0.006160
         61  0.639554   0.001766

[989426 rows x 2 columns]

In [10]:
_ds

             latitude  longitude
track_id t
239      0        168         87
         1        168         86
         2        168         84
         3        168         83
         4        168         82
...               ...        ...
511825   57       189          6
         58       190          4
         59       190          3
         60       191          1
         61       191          0

[989426 rows x 2 columns]