In [18]:
import pandas as pd
parquet = '../output/models/custom_ds_latent_size_128a_fivo_adamw/logprob.parquet'

_ds = pd.read_parquet(parquet)

In [28]:
_ds.index.levels[0]

Index([    6,    10,    25,    31,    32,    33,    37,    51,    53,    58,
       ...
       65503, 65509, 65512, 65514, 65520, 65521, 65522, 65530, 65532, 65533],
      dtype='uint16', name='track_id', length=14228)

In [30]:
lat_lon_ds = pd.read_parquet('../new_data/ais_test_by_bins.parquet')

In [32]:
lat_lon_ds.index.levels[0]

Index([   239,    299,    332,    358,    404,    447,    459,    468,    481,
          488,
       ...
       511605, 511628, 511641, 511648, 511651, 511684, 511695, 511727, 511742,
       511825],
      dtype='int64', name='track_id', length=15814)

In [21]:
lat_lon_ds

             latitude  longitude
track_id t
239      0        168         87
         1        168         86
         2        168         84
         3        168         83
         4        168         82
...               ...        ...
511825   57       189          6
         58       190          4
         59       190          3
         60       191          1
         61       191          0

[989426 rows x 2 columns]

In [ ]:
_ds = pd.merge(_ds, lat_lon_ds, how='inner', left_index=True, right_index=True)

In [25]:
_ds

              log_prob  latitude  longitude
track_id t
3147     0  -49.487236       213        110
         1  -58.450813       212        109
         2  -46.560780       210        108
         3  -51.277756       208        107
         4  -42.681595       207        107
...                ...       ...        ...
11536    27 -36.707634       213         30
         28 -14.695847       211         32
         29 -17.283325       210         34
         30 -10.318414       209         35
         31 -16.975281       209         35

[104703 rows x 3 columns]